ISA ?= native
# ISA ?= x86
NAVY_HOME ?= /home/rexxar/PA2021_0308/ics2018/navy-apps
ifeq ($(NAVY_HOME), )
  $(error Must set NAVY_HOME environment variable)
endif

$(shell mkdir -p $(NAVY_HOME)/fsimg/bin/ $(NAVY_HOME)/fsimg/dev/)
