NAME = am
SRCS = $(shell find -L ./arch/$(ARCH)/src/ -name "*.c" -o -name "*.cpp" -o -name "*.S")
LIBS += klib
export AM_HOME ?= /home/rexxar/PA2021_0308/ics2018/nexus-am
include $(AM_HOME)/Makefile.lib
